---

- name: Run show ARP and Interface Brief commands on routers
  hosts: cisco-routers
  
  tasks:
  
    - name: show arp
      ios_command:
        commands: 
          - show arp
          - sh ip int brief
        provider: "{{ cli }}"
      register: result
      
    -name: Show result
     debug: var = result.stdout_lines
     
     
     