---

- name: Gather facts of routers
  hosts: cisco-routers
  
  tasks:
  
    - name: show arp
      - ios_facts:
          gather_subset: all
          provider: "{{ cli }}"
      
    - name: Show arp result
      debug: var = result.stdout_lines[0]
     
    - name: Show int br result
      debug: var = result.stdout_lines[1]
      
    - name: Create all_facts dir
      file:
        path: ./all_facts/
        state: directory
        mode: 0755
       
    - name: Copy facts to file
      copy:
        content: "{{ ios_facts_result | to_nice_json }}"
        dest: "all_facts/{{inventary_hostname}}_facts.json"
     
     
     